services:
  - type: web
    name: my-portfolio
    env: node
    rootDir: my-portfolio
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22
